---
- include_role:
    name: computate.computate_powertools
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ APP_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed
- name: Create the directory {{ APP_SRC }}
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: Check for the {{ APP_NAME }} README file
  stat:
    path: "{{ APP_SRC }}/README.md"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO_SSH }} source code into {{ APP_SRC }}"
  ansible.builtin.git:
    repo: "{{ APP_REPO_SSH }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  ignore_errors: true
  when: not APP_README_PATH.stat.exists
  register: CLONE_REPO
- name: "Clone the {{ APP_REPO_HTTPS }} source code into {{ APP_SRC }}"
  ansible.builtin.git:
    repo: "{{ APP_REPO_HTTPS }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists and CLONE_REPO.failed
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"
    mode: 0775

