---
- name: "Install powertools dependencies: dnf-plugins-core"
  shell: "pkcon install -y dnf-plugins-core"
  ignore_errors: true
- name: "Enable powertools repo"
  shell: "pkcon repo-enable powertools"
  ignore_errors: true
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }}"
  loop: "{{ APP_DEPENDENCIES }}"
  ignore_errors: true
- name: Create the directory {{ APP_SRC }}
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: Check for the {{ APP_NAME }} README file
  stat:
    path: "{{ APP_SRC }}/README.md"
  register: APP_README_PATH
- name: Clone the {{ APP_REPO }} source code into {{ APP_SRC }}
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"
    mode: 0775

